apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "obs-frontend.fullname" . }}-config
  labels:
    {{- include "obs-frontend.labels" . | nindent 4 }}
data:
  # Environment variables
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  VITE_APP_BASE_API: {{ .Values.env.VITE_APP_BASE_API | quote }}
  VITE_APP_BASE_API_METRICS: {{ .Values.env.VITE_APP_BASE_API_METRICS | quote }}
  VITE_APP_BASE_API_AVAILABILITY: {{ .Values.env.VITE_APP_BASE_API_AVAILABILITY | quote }}
  VITE_APP_BASE_API_DOMAIN: {{ .Values.env.VITE_APP_BASE_API_DOMAIN | quote }}
  VITE_APP_BASE_API_AIAGENT: {{ .Values.env.VITE_APP_BASE_API_AIAGENT | quote }}
  VITE_APP_USER_API: {{ .Values.env.VITE_APP_USER_API | quote }}
  VITE_APP_CORE_API: {{ .Values.env.VITE_APP_CORE_API | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "obs-frontend.fullname" . }}-nginx-config
  labels:
    {{- include "obs-frontend.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Values.nginx.config | indent 4 }}
